version: "3.3"
services:
  postgres_vector:
    image: pgvector/pgvector:pg17
    env_file: .env_sample
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgres
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

volumes:
  postgres_volume: